# Generated by Django 3.2.6 on 2021-09-07 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ('-date',), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
