# Generated by Django 3.2.6 on 2021-09-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_comments_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='status',
        ),
    ]
